### ISSUE TITLE
expose gcloud && kubectl

### ISSUE THREAD

**Issue by yoshuawuyts** [buildkite/charts#6]
This might be something for the buildkite agent image, but currently to create a full builder that can perform redeploys as a first step in my pipeline I need to do:

``` yaml
steps:
  - name: ":ubuntu: setup"
    command: >
      export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)";
      echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" \
        | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list;
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
        | sudo apt-key add -;
      sudo apt-get update;
      sudo apt-get -y install google-cloud-sdk;
      sed -i -e 's/true/false/' \
        /usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/config.json;
      gcloud components install -q kubectl;
      PATH="/usr/lib/google-cloud-sdk/bin:$PATH";
      kubectl get pods;
```

And in the template, to inherit config from the compute node I had to mount the `gcloud` config:

``` yaml
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: buildkite-agent-builder-private-git
        heritage: helm
    spec:
      containers:
        - name: buildkite-agent
          image: buildkite/agent:ubuntu-docker
          volumeMounts:
            - name: var-lib-docker
              mountPath: /var/lib/docker
            - name: home-anon-config-gcloud
              mountPath: /home/anon/.config/gcloud
      volumes:
        - name: var-lib-docker
          emptyDir: {}
        - name: home-anon-config-gcloud
          hostPath:
            path: /home/anon/.config/gcloud
```

I think it would make sense to add this to the buildkite images / charts in some way so people who want to perform deploys don't need to add this as boilerplate. Perhaps we need a new type that includes this? - idk. Thanks! :sparkles:
