### ISSUE TITLE
health checks

### ISSUE THREAD

**Issue by yoshuawuyts** [buildkite/charts#7]
sometimes the docker socket can get unmounted for reasons; adding a health check can be beneficial:

``` yaml
          livenessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 1
            exec:
              command:
                - sudo
                - docker
                - ps
```
### See Also
- http://kubernetes.io/docs/user-guide/liveness/
